# Generated by Django 2.0.4 on 2018-07-10 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagelike',
            old_name='user',
            new_name='liked_by',
        ),
    ]
