# Generated by Django 2.0.4 on 2018-07-10 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20180710_0355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedimage',
            name='approved',
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Refused', 'Refused'), ('Accepted', 'Accepted')], default='Pending', max_length=10),
        ),
    ]
