# Generated by Django 2.0.4 on 2018-07-10 18:15

from django.db import migrations, models
import website.paths


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20180710_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedimage',
            name='small_image',
            field=models.ImageField(default=1, upload_to=website.paths.url_gallery_img_small),
            preserve_default=False,
        ),
    ]
