# Generated by Django 2.0.4 on 2018-07-10 21:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_remove_uploadedimage_small_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadedimage',
            old_name='date',
            new_name='uploaded_on',
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='date_taken',
            field=models.DateField(default=datetime.datetime(2018, 7, 10, 21, 22, 0, 504761, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
