# Generated by Django 2.0.4 on 2018-07-10 22:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import website.paths


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0008_auto_20180710_2229'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(upload_to=website.paths.url_user_img)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='data', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='userdefaults',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserDefaults',
        ),
    ]
