# Generated by Django 2.0.4 on 2018-07-10 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_uploadedimage_sample'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedimage',
            name='sample',
        ),
    ]
