# Generated by Django 2.0.4 on 2018-07-10 23:42

from django.db import migrations, models
import website.paths


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_remove_uploadedimage_sample'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedimage',
            name='sample',
            field=models.ImageField(default=1, upload_to=website.paths.url_gallery_img_small),
            preserve_default=False,
        ),
    ]
