# Generated by Django 2.0.4 on 2018-07-11 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_uploadedimage_sample'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadedimage',
            old_name='sample',
            new_name='thumbnail',
        ),
    ]
